#14/tab bar view
DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA pull request #20
Opened 2023-07-17 12:23 UTC by ChangJin-Lee

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- #14 

👷 **작업한 내용**
- TabBarView를 완성해요
- custom TabBar를 만들고 각 Tab에 뷰를 연결할 수 있게 해요

## 🚨 참고 사항
- 컬러와 이미지 에셋을 디자이너가 확인해야해요.

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|완성된 뷰 |<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/04f745f8-c896-4fc5-8761-c50bb0fa7e13">

## 📟 관련 이슈
- Resolved: #

2023-07-17 12:32 UTC, mollangcow commented
2,3,4번 탭에서 영수증 스캔하기
버튼 없어야 해요!

2023-07-17 13:12 UTC, ChangJin-Lee commented
네 모카. 
2,3,4번 탭에서 영수증 스캔하기 버튼이 없어지도록 만들었어요

2023-07-17 14:54 UTC, wonniiii requested changes

2023-07-17 15:05 UTC, ChangJin-Lee commented on SickSangHae/View/TabBarView.swift
> +                Spacer()
네 워니. 
TabView를 사용하는 방법으로 구현한 내용은 다음과 같아요.
TabView에서는 영수증 스캔하기를 구현하기 힘들었어요.
또한 탭을 클릭했을 때 텍스트와 아이콘의 색깔이 변하는 것을 구현하기 어려웠어요.

```
struct TabBarView: View {
    // views에 다른 뷰를 넣으면 돼요. 현재는 알아보기 쉽게하기 위해 color를 넣어 두었어요.
    let views: [Color] = [ .yellow, .blue, .green, .indigo]
    let icons = ["bag.fill", "chart.bar", "newspaper.fill", "circle.inset.filled"]
    let tabbarItems = [ "나의 냉장고", "통계", "보관함", "설정" ]
    
    var body: some View {
        TabView {
            ForEach(views.indices, id: \.self) { index in
                views[index]
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                    .tag(index)
                    .tabItem {
                        Image(systemName: icons[index])
                        Text(tabbarItems[index])
                    }
            }
        }
    }
}
````

이를 해결하기 위해 enum으로 각 탭을 정의해주고 
custom tab bar를 만들었어요.


### 참고 사항
- 다음의 유튜브를 참고했어요.
- https://www.youtube.com/watch?v=v19fln0e_qQ

2023-07-17 15:16 UTC, ChangJin-Lee commented on SickSangHae/View/TabBarView.swift
> +                            .padding(.bottom, -12.adjusted)
네 워니. 
on-sided corner를 만들기 위해 생각해낸 간단한 접근법이었어요. 
양수 패딩과 음수 패딩을 두 번 사용해서 제 자리에서 윗 부분만 cornerRadius를 줄 수 있다고 생각했어요.

다음처럼 양수 패딩만 적용하고 cornerRadius를 적용했을 때 윗 부분만 cornerRadius가 적용돼요.
하지만 제 자리로 돌아오기 위해서 같은 값 만큼 음수 패딩을 적용했어요.

```
                            .padding(.bottom, 12.adjusted)
                            .cornerRadius(12.adjusted)
//                            .padding(.bottom, -12.adjusted)
```
### 
|기능|스크린샷|
|:--:|:--:|
|양수 패딩만 <br/>적용한 경우|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/1b73d64a-722b-4568-9fb4-700a1a6a7fcd" width = 40%>
|양수 패딩과  <br/> 음수 패딩을 <br/>적용한 경우|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/8d1acac5-7c22-4f3f-a93c-1b9fcb5ba23a" width = 40%>

### 참고사항 
- 다른 방법이나 의견이 있다면 언제든 환영합니다.

2023-07-17 15:19 UTC, ChangJin-Lee commented on SickSangHae/View/TabBarView.swift
> +                    }
좋은 의견 고마워요. 
코드에 반영했어요. 코드 수가 줄어들고 가독성도 좋아졌어요.
다음과 같이 변경했어요.

```
VStack{
                        Image(systemName: "chart.bar.xaxis")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 25)
                        Text("통계")
                            .font(.system(size: 14.adjusted))
                        }
                        .foregroundColor(selectedTab == .ChartView ? .mint : .gray)
```

2023-07-17 15:25 UTC, wonniiii commented on SickSangHae/View/TabBarView.swift
> +                            .padding(.bottom, -12.adjusted)
이 부분은 생각지도 못했네요 ! 새로운 접근법 덕분에 배워갑니다 ! 감사해요 CJ.

2023-07-17 15:28 UTC, wonniiii commented on SickSangHae/View/TabBarView.swift
> +                Spacer()
색깔이 변하는 부분은 accnetColor를 이용하면 되긴 하는데 확실히 영수증 스캔하기 버튼은 저도 더 생각해봐도 떠오르질 않네요.. 버튼으로 구현하기 번거로우셨을텐데 고생많으셨어요 !

2023-07-17 15:30 UTC, wonniiii approved these changes
변경사항 잘 확인했습니다 ! 고생많으셨어요 CJ !

2023-07-17 15:36 UTC, ChangJin-Lee commented on SickSangHae/View/TabBarView.swift
> +                Spacer()
맞네요. accentColor가 있었군요.
좋은 정보 감사합니다. 배워가요. 워니.

2023-07-18 01:59 UTC, merged

2023-07-24 09:49 UTC, unnnyong commented on SickSangHae/View/TabBarView.swift
> +    case SettingView
lower camel..case... 🐫 ... 🐪 ..

2023-07-24 17:10 UTC, ChangJin-Lee commented on SickSangHae/View/TabBarView.swift
> +    case SettingView
고마워요 영. 
CaseIterable 프로토콜을 사용해 코드를 수정했어요. 
밑의 풀리퀘에서 확인 가능합니다. 
https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/pull/48